server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    #关闭表示 eureka不向自己注册自己，也不注册到别的eureka里面，在eureka集群下面要设置true 默认是true
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
